version: '3'
services: 
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: 
      - ./docker/app/.env:/.env
    depends_on: 
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgresql
    ports: 
      - "127.0.0.1:5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gocontacts
  nginx:
    image: nginx:latest
    volumes: 
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports: 
      - "127.0.0.1:80:80"
    depends_on: 
      - app
    restart: always
volumes: 
  postgres_data: